### ISSUE TITLE
Installer Trips AV - Source won't start

### ISSUE THREAD

**Issue by eglische** [qinyan-alpha/osr2_control_app#1]
Hello!

The used packer for the installer trips Avast. So i had a look at the raw files. (Maybe you go with another installer in the future?)
Installed the Python 3.10.6 amd64 runtime, had to modify the run.bat to point to the exact location of python.exe

The start_Ui.py does nothing for me, it just starts python and shuts it down again.
Given my limited know how i can't troubleshoot it further, there are no logfiles i can find neither from your script nor from phyton itself

Cheers

**Comment by qinyan-alpha** [comment]
I will test the program on my other Windows PC later. If it works for me, the issue may be with how you are launching it. Please use the installer provided in the Releases to install the project to a suitable location. After installing, there should be an executable file called "startui.exe". This should be able to launch the program normally since the installer extracts all required dependencies and the Python interpreter.

Also, please check that you are on a Windows device - it will not run on other platforms. If the problem persists, I can provide an exe with cmd and a run(cmd).bat file. If you know bat file syntax, you can try running the bat file and keeping the terminal open after instead of exiting, to check for any issues.

Let me know if you have any other questions! I appreciate you taking the time to test this program and provide feedback - it will help improve the software. Please don't hesitate to reach out if you need any other assistance getting it running properly.

Below is an image showing the files and folders under the install location when the program is installed properly:
![QQ截图20240123214635](https://github.com/qinyan-alpha/osr2_control_app/assets/76674227/5682b98a-c1a5-4643-abe0-afa904ea72d2)

**Comment by qinyan-alpha** [comment]
no module named pywin32.
you can fix it by:
run cmd
.\python-3.10.6\python.exe -m pip install pywin32.
or Download new Releases.

**Comment by eglische** [comment]
hello, yes now it fires up, in addition i had to install over pip following modules too:
PySide6
serial
pyserial

have to test the serial connection tho, but thanks!
